name: flutter_open_chinese_convert
description: flutter_open_chinese_convert bridges OpenCC (Open Chinese Convert, 開放中文轉換) to your Flutter projects.
version: 1.0.0
homepage: https://github.com/zonble/flutter_open_chinese_convert

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: net.zonble.flutter_open_chinese_convert
        pluginClass: FlutterOpenccPlugin
      ios:
        pluginClass: FlutterOpenccPlugin
